# Generated by Django 4.2.9 on 2025-03-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callAPI', '0002_call_conversation_delete_callinteraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_ai', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='call',
            name='duration',
        ),
        migrations.AlterField(
            model_name='call',
            name='prompt',
            field=models.TextField(default='You are a helpful assistant. Listen carefully and respond appropriately.'),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='callAPI.call'),
        ),
    ]
