# Generated by Django 4.2.9 on 2025-04-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callAPI', '0004_mediafile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
        migrations.AlterModelOptions(
            name='conversationturn',
            options={},
        ),
        migrations.AddField(
            model_name='call',
            name='total_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='conversationturn',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
