# Generated by Django 4.2.9 on 2025-04-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callAPI', '0005_delete_mediafile_alter_conversationturn_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='call',
            name='voice',
        ),
    ]
