# Generated by Django 4.2.9 on 2025-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callAPI', '0006_remove_call_prompt_remove_call_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='conversation',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ConversationTurn',
        ),
    ]
