# Generated by Django 4.2.9 on 2025-04-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callAPI', '0007_call_conversation_delete_conversationturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10),
            preserve_default=False,
        ),
    ]
