# Generated by Django 4.2.9 on 2025-04-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callAPI', '0008_call_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='direction',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10),
        ),
    ]
