# Generated by Django 4.2.9 on 2025-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callAPI', '0010_alter_call_call_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='conclusion',
            field=models.JSONField(default=list, null=True),
        ),
    ]
